### PR TITLE
subjects can collide

### PR DESCRIPTION
**Pull request by notabigthreat**

### CODE REVIEW

**Comment by notabigthreat** [comment]
that requires validation on visual and proof-reading

**Comment by jab9k3** [comment]
I haven't forgotten you just got home after a few months lot to do. I'll
work on sfml setup and some other stuff asap I have a lot to learn

**Comment by notabigthreat** [comment]
well i think it's okay for now, merging

**Comment by jab9k3** [comment]
hey dude wutsup thanks for keepin busy on this i appreciate it. Ive been
workin through some C++ and sfml tutorials im tryin to finish the sfml one
before i start with our code. This is my first
project like this so im a bit lost but should be able to catch up soon

**Pull request merged**
